# Site settings
title: Edouard Richard
twitter_username: travlel_ed
name: Edouard Richard

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Site
   url: https://ch-montperrin.fr/
 - title: GitHub
   url: https://github.com/Traveled
#  - title: DZone
  #  url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/%C3%A9douard-richard-a6a80749


#Any buzzword skills you want to include
skills:
 - Vmware
 - Citrix
 - Microsoft
 - Slick
 - Product management
 - API design
 - Groovy
 - Spring MVC/Boot/Social
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Architechte systeme
   start: 2008
   end: Ongoing
   employer: Centre Hospitalier Montperrin
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2007
   end: 2008
   employer: EDL
   description: Responsable service reprographe et station manip radio.

#Education is required
education:
 - level: BTS IRIS
   date: 2007
   subject: Informatique et reseau pour l'industrie et les services
   school: Lycee Vauvenargues Aix en Provence
 - level: Bachelor of Science (Bac SSI)
   date: 2005
   subject: Artificial Intelligence and Computer Science
   school: Lycee Val de Durance Pertuis

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
    #   date: September 16, 2013
    # - title: Algorithms Design and Analysis, Part 1
    #   link: https://www.coursera.org/specializations/algorithms
    #   optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
    #   date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - Traveled/Traveled.github.io
 - Traveled/ScaLambda
 - Traveled/opinionated-akka-http
 - Traveled/food2vec
 - Traveled/microservices
 - Traveled/spring-social-geeklist
 - Traveled/spring-social-stackoverflow
 - Traveled/genotype
 - Traveled/footweets
 - Traveled/ElasticSearchGradle

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  Administrateur, architecte avec plus de 13 ans d'expérience, j’ai accompagné la transformation numérique des métiers. Munis d’un fort background technique j’assure la transversalité entre le design du Datacentre et l’exécution des évolutions, aussi bien sur un socle On-Premise que Edge ou Cloud et avec des technologies libres ou propriétaires.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>• INFRASTRUCTURE</strong>: Vsphere V8.0 / Citrix Hypervisor 8.2 / PureStorage, Dell Emc, FC Brocade, Reseau H3C-Hpe
   <strong>• ENVIRONEMENT</strong>: MICROSOFT 2019-2022: AD, SYSTEM CENTER, EXCHANGE, BASTILLION, WSUS, CLUSTERS MS, IPAM, MSSQL, AZURE, OFFICE 2021   CITRIX 2203: XENAPP, ADC, PVS, MCS, WEM / HCI, VDI / LINUX, UNIX / ILEX IAM & SSO, SIEM
   <strong>• SUPERVISION-GESTION</strong> SCOM, PRTG, NAGIOS, LIBRENMS, TIG STACK / SCCM, DELL OME, WMS/ ADAUDIT+, GRAYLOG, ELASTICSEARCH, WINDOWS ADMIN CENTER, GLPI, SKYLINE/ANSIBLE, CHEF, PUPPET, GIT 
   <strong>• SÉCURITÉ & SAUVEGARDE</strong>: CHECKPOINT +FORTINET / OTP-2FA-SMARTCARD / ATEMPO TINA / VEEAM / CYBERWATCH / PROOFPOINT
   <strong>• LANGUAGES</strong>: PowerShell (Expert), Bash, .Net, C#, Python 
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
